### ISSUE TITLE
在uniapp编译微信小程序中使用变量进行存储这个会抛出TypeError: Converting circular structure to JSON错误 但是可以使用 希望能解决这个问题。谢谢

### ISSUE THREAD

**Issue by MR-ZiWeiter** [landn172/lottie-miniapp#102]
**bug描述**
按照说明进行使用时 得到错误TypeError: Converting circular structure to JSON

**复现过程**
1、正常获取canvas对象
2、在data中定义变量  初始化容器后并赋值给定义变量
3、得到错误

**期望**
希望解决这个错误

**截图**
![image](https://user-images.githubusercontent.com/24221311/66542917-709c6500-eb66-11e9-9386-8e8c46011879.png)

**错误设备信息**
 uniapp版本2.0.0-23320190923002
 微信开发者工具 1.02.1909292
 node 12.7.0

**Comment by landn172** [comment]
看错误堆栈情况是uniapp的问题。把动画json发出来看看。

**Comment by landn172** [comment]
@MR-ZiWeiter 我测试了下没问题，检查下你自己的代码。
![image](https://user-images.githubusercontent.com/4362412/66553261-5d48c400-eb7d-11e9-9443-5ba7b15d666f.png)

**Comment by landn172** [comment]
与基础库无关
![image](https://user-images.githubusercontent.com/4362412/66553495-cc261d00-eb7d-11e9-8daa-400e69716edf.png)

**Comment by landn172** [comment]
首先你为什么要在data声明`thisLottie`，完全没有必要，这是导致你这个问题的根本原因。

**Comment by MR-ZiWeiter** [comment]
因为想单独对每一个进行控制，使用name方式也行 但是稍麻烦  谢谢您耽误宝贵时间的解答 非常感谢
