### ISSUE TITLE
请问一下如何处理含有图片的lottie json？

### ISSUE THREAD

**Issue by jasonxxp** [landn172/lottie-miniapp#11]
请问一下如何处理含有图片的lottie json？
试了下会报错，image放到各个地方也不行。求大神解答~~
json例子如下：https://share.weiyun.com/5DKQSpa

**Comment by jasonxxp** [comment]
目前会报错：Cannot read property 'assetsPath' of undefined;at index/index page lifeCycleMethod onReady function
TypeError: Cannot read property 'assetsPath' of undefined

**Comment by landn172** [comment]
@jasonxxp  已修复 v1.3.3
