### ISSUE TITLE
uni-app下可以使用，但h5有报错（不影响使用）

### ISSUE THREAD

**Issue by zc95** [landn172/lottie-miniapp#110]
**bug描述**
1. uni-app编译之后h5端运行报错
> [system] API `getFileSystemManager` is not yet implemented
> [system] TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.

**复现过程**
1. 我是用了uni-app进行多端开发
2. 代码 https://github.com/zc95/uni-app-lottie

**期望**
希望作者可以帮忙解决一下呢～

**截图**
<img width="1163" alt="WX20191104-231643@2x" src="https://user-images.githubusercontent.com/21879812/68132681-0eaeff80-ff5a-11e9-84c7-2c1c5417f68f.png">

**错误设备信息**
 - Device: [chrome 开发者模式]
 - OS: [macOS Mojave]
 - Browser [chrome]
 - Version [77.0.3865.90（正式版本） （64 位）]

**Comment by landn172** [comment]
@zc95 只支持小程序端。h5端用官方的库，api都一样的。

**Comment by iimeepo** [comment]
@zc95 H5端条件编译引用官方的lottie-web库，我用的是document获取dom节点操作的可以实现，uni或者vue怎样操作dom都不行，有解决方案记得艾特我

**Comment by wzzzzzz** [comment]
> 感谢你！救了我

**Comment by bibiuc** [comment]
> @zc95 H5端条件编译引用官方的lottie-web库，我用的是document获取dom节点操作的可以实现，uni或者vue怎样操作dom都不行，有解决方案记得艾特我

  自己封装组件的话加个
```
context:this
```
