### ISSUE TITLE
base64图片读取失败&本地资源图片打包后路径错误

### ISSUE THREAD

**Issue by iimeepo** [landn172/lottie-miniapp#112]
**bug描述**
注：我使用的是uni-app混合开发
1.犸良上面打包下载的json文件中包含base64图片资源，在编译到小程序端的时候使用正常，编译到APP的时候会报错，显示读取写入base64资源失败；
2.json文件中包含本地图片路径，u参数写的是相对目录，p参数写的是文件名称，编译后会按实际生成的页面page文件的位置相对定位，而不是json文件的位置相对定位（导出的json文件是按该文件位置定位的引入图片），目前我的处理方式是：u参数为空，p参数为图片的绝对路径，可以正常运行，不确定这个是不是bug，还是说我处理的方式不对。
代码参考：@zc95  ：  https://github.com/zc95/uni-app-lottie

**期望**
希望可以优化支持base64图片编码，或者是有方案处理下犸良导出的文件。

**截图**
![image](https://user-images.githubusercontent.com/20764007/68522307-dfdfb300-02e4-11ea-876f-75f39cf1ce53.png)

**错误设备信息**
 - Device: iPhone7
 - OS: iOS12.4.1
  - Version lottie-miniapp： 1.8.8

**Comment by landn172** [comment]
@iimeepo 只支持小程序端，如果需要其他端的支持用官方的lottie-web等

**Comment by iimeepo** [comment]
我看了下源码，是小程序里的文件管理方法在uni-app里不适用，没办法保存读取base64文件，准备用本地图片替代了，等后续uni-app官方出了对应的api之后在用。点个赞，还是很好用的。
