### ISSUE TITLE
小程序 使用时间长 会显示 base64报错 

### ISSUE THREAD

**Issue by changyiger123** [landn172/lottie-miniapp#116]
**bug描述**
小程序 使用时间长 会显示 base64报错 
因为有几种不同的动画进行切换 加载不同的动画 会产生图片缓存 

麻烦有时间帮忙看一下 谢谢

**复现过程**
反复加载lottie动画时候会产生

**期望**

**截图**
![image](https://user-images.githubusercontent.com/22109669/68912636-a5b65b80-0793-11ea-8fe5-ac9b28f94f24.png)

**错误设备信息**

**Comment by landn172** [comment]
@changyiger123 已修复 lottie-miniapp@1.8.10

**Comment by changyiger123** [comment]
thank you



    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            445160930
                            
                            
                                
                                    邮箱：445160930@qq.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            在2019年11月18日 09:37，landn172 写道： Closed #116.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/landn172/lottie-miniapp/issues/116?email_source=notifications\u0026email_token=AFIV3ZJKVZUBV5YDFYXY5MTQUHWV3A5CNFSM4JNUUKD2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOU47FS7A#event-2805881212",
"url": "https://github.com/landn172/lottie-miniapp/issues/116?email_source=notifications\u0026email_token=AFIV3ZJKVZUBV5YDFYXY5MTQUHWV3A5CNFSM4JNUUKD2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOU47FS7A#event-2805881212",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
