### ISSUE TITLE
更新了最新的版本号 动画在手机上显示不出来  在微信开发者工具上是好的 没更新之前是好的

### ISSUE THREAD

**Issue by changyiger123** [landn172/lottie-miniapp#121]
**bug描述**
更新了最新的版本号 动画在手机上显示不出来  在微信开发者工具上是好的 没更新之前是好的

**复现过程**
这一张是开发者工具所展示
![IMG_4313](https://user-images.githubusercontent.com/22109669/69211628-9cfdc500-0b99-11ea-9ced-528d840bbb9c.JPG)

这一张是手机上所显示 

![IMG_4312(20191120-132532)](https://user-images.githubusercontent.com/22109669/69211615-9707e400-0b99-11ea-8f90-ce55d69d5086.PNG)

**期望**

**截图**

**错误设备信息**

**Comment by landn172** [comment]
@changyiger123 有没有报错

**Comment by changyiger123** [comment]
我们线上小程序 叫 饲养员之家&nbsp; &nbsp;是上一版本的 那个没问题 你可以看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"landn172"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 中午1:36
收件人:&nbsp;"landn172/lottie-miniapp"<lottie-miniapp@noreply.github.com&gt;;
抄送:&nbsp;"常建"<445160930@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [landn172/lottie-miniapp] 更新了最新的版本号 动画在手机上显示不出来  在微信开发者工具上是好的 没更新之前是好的 (#121)




@changyiger123 有没有报错

**Comment by changyiger123** [comment]
没有报错 就是动画真机上不出来

**Comment by changyiger123** [comment]
没有报错&nbsp; 更新之前是好的 现在真机上是出现不了了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"landn172"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月20日(星期三) 中午1:36
收件人:&nbsp;"landn172/lottie-miniapp"<lottie-miniapp@noreply.github.com&gt;;
抄送:&nbsp;"常建"<445160930@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [landn172/lottie-miniapp] 更新了最新的版本号 动画在手机上显示不出来  在微信开发者工具上是好的 没更新之前是好的 (#121)




@changyiger123 有没有报错

**Comment by landn172** [comment]
@changyiger123 找到问题了，上次修改base64图片问题改动导致的。已修复 lottie-miniapp@1.8.11

**Comment by changyiger123** [comment]
嗯 谢谢
