### ISSUE TITLE
加载时候 会不定时的出现  解析动画 小bug

### ISSUE THREAD

**Issue by changyiger123** [landn172/lottie-miniapp#125]
**bug描述**
进入动画所在页面之后  然后进入其他页面 之后再返回动画页面 会产生动画变大然后有时候在网络不好的情况下会卡死的错误

**复现过程**

**期望**

**截图**
![Uploading image.png…]()

**错误设备信息**

**Comment by changyiger123** [comment]
![image](https://user-images.githubusercontent.com/22109669/69403727-4c6f9e80-0d36-11ea-9268-10b340031cc5.png)

**Comment by changyiger123** [comment]
请帮忙看下 谢谢

**Comment by landn172** [comment]
@changyiger123 把对应的json文件发出来

**Comment by changyiger123** [comment]
https://7niu-article.galaxyeye-tech.com/miniprograme/pets/data/catLick.v1.json

**Comment by landn172** [comment]
没有复现这个问题，demo： https://github.com/landn172/lottie-miniapp/tree/issues-125。可能你做了其他的处理导致的。

**Comment by changyiger123** [comment]
嗯 这个问题不是很容易出现  我再看看吧
