### ISSUE TITLE
如何得到一个透明背景而不是黑色？

### ISSUE THREAD

**Issue by XdyGoGo** [landn172/lottie-miniapp#129]
如何得到一个透明背景而不是黑色？

**Comment by landn172** [comment]
canvas本来就是透明的啊，默认没有设置背景，不懂？？？

**Comment by XdyGoGo** [comment]
bug 现在真机iphoneX出来动画就是黑色背景的

**Comment by landn172** [comment]
其他手机没问题还是就iPhone有问题，把对应的json发出来

**Comment by XdyGoGo** [comment]
[data.json.js.txt](https://github.com/landn172/lottie-miniapp/files/3885370/data.json.js.txt)
暂时只有iphoneX可以测试 身边无其他手机
    const canvasContext = wx.createCanvasContext('test-canvas');
    //  请求到的lottie json数据
    const animationData = this.data.dataJson;
    // 请求lottie的路径。注意开启downloadFile域名并且返回格式是json
    const animationPath = 'https://github.com/landn172/lottie-miniapp/files/3147067/font.txt';

    // 指定canvas大小
    canvasContext.canvas = {
      width: 200,
      height: 200
    };

    // 如果同时指定 animationData 和 path， 优先取 animationData
    lottie.loadAnimation({
      renderer: 'canvas', // 只支持canvas
      loop: true,
      autoplay: true,
      animationData: animationData,
      path: animationPath,
      rendererSettings: {
        context: canvasContext,
        clearCanvas: true
      }
    });

**Comment by landn172** [comment]
最近没有时间看这个问题，之后有时间看看问题。现在web上测试下是不是和预期一样。 @XdyGoGo

**Comment by landn172** [comment]
看了下这个动画本身就是黑色背景
