### ISSUE TITLE
带有蒙版的json显示又问题

### ISSUE THREAD

**Issue by wuearl** [landn172/lottie-miniapp#134]
[loading.json.zip](https://github.com/landn172/lottie-miniapp/files/3926335/loading.json.zip)

**bug描述**

**复现过程**

**期望**

**截图**

**错误设备信息**

**Comment by landn172** [comment]
问题描述清楚（附带截图），并且期望达到什么。还有在web上的canvas表现如何，是否和小程序表现一致。

**Comment by wuearl** [comment]
![image](https://user-images.githubusercontent.com/31372199/70305492-81541900-183f-11ea-8d96-2d64208dd16a.png)
这是小程序截图
![image](https://user-images.githubusercontent.com/31372199/70305509-8b761780-183f-11ea-9a12-b967f32ca641.png)
这是web截图
谢谢你的回复，

**Comment by wuearl** [comment]
![image](https://user-images.githubusercontent.com/31372199/70305567-b3657b00-183f-11ea-8063-d5321d1c3621.png)
这是小程序截图

![image](https://user-images.githubusercontent.com/31372199/70305673-f3c4f900-183f-11ea-81a6-ed34baffa5ab.png)
这是web截图
感谢你的回复

**Comment by landn172** [comment]
测试过了不支持。
