### ISSUE TITLE
HTMLCanvasView is not defined请问现在有解吗

### ISSUE THREAD

**Issue by ioslide** [landn172/lottie-miniapp#135]
**bug描述**
HTMLCanvasView is not defined

**截图**
![QQ截图20191206151237](https://user-images.githubusercontent.com/41772864/70304018-ec035580-183b-11ea-8681-6ef82fead1d6.jpg)

**Comment by landn172** [comment]
这个错误应该和微信开发者工具有关

**Comment by ioslide** [comment]
> 这个错误应该和微信开发者工具有关

哦哦，忘记说了，这个是真机调试显示错误并报错，微信开发者工具显示正常没报错
