### ISSUE TITLE
支付宝小程序  错误：api.base64ToArrrayBuffer is not a function

### ISSUE THREAD

**Issue by liuyunzyj** [landn172/lottie-miniapp#142]
![image](https://user-images.githubusercontent.com/40293335/72238979-6e8ceb00-361a-11ea-82a4-f6a6c36ce845.png)
![image](https://user-images.githubusercontent.com/40293335/72239008-85334200-361a-11ea-8a2a-7392233c8649.png)
![image](https://user-images.githubusercontent.com/40293335/72239013-8a908c80-361a-11ea-80fc-f72687450f3f.png)
![Uploading image.png…]()

**Comment by liuyunzyj** [comment]
@landn172 麻烦请看看

**Comment by landn172** [comment]
你的小程序基础库版本？

**Comment by landn172** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/base/wx.base64ToArrayBuffer.html
base64ToArrayBuffer 2.4 起支持

**Comment by liuyunzyj** [comment]
微信小程序是没有问题的，就是支付宝小程序出这个错误了

**Comment by landn172** [comment]
支付宝没有这个base64ToArrayBuffer api

**Comment by liuyunzyj** [comment]
所以出错了啊is not function

**Comment by landn172** [comment]
@liuyunzyj 支付宝不支持带有base64的json

**Comment by landn172** [comment]
@liuyunzyj 昨天研究了下支持支付宝base64 #143， 升级到lottie-miniapp@1.8.12

**Comment by liuyunzyj** [comment]
好的

**Comment by jetBn** [comment]
> 好的

支付宝能用了吗
