### ISSUE TITLE
支付宝小程序报错

### ISSUE THREAD

**Issue by jetBn** [landn172/lottie-miniapp#146]
![image](https://user-images.githubusercontent.com/26957220/78756989-507f1e80-79ae-11ea-82df-d684f27d3a7a.png)

**Comment by jetBn** [comment]
![image](https://user-images.githubusercontent.com/26957220/78757016-6096fe00-79ae-11ea-95d9-78b8a5579806.png)

**Comment by jetBn** [comment]
还有在微信小程序中正常 支付宝小程序中动画模糊

**Comment by landn172** [comment]
把你的json文件发出来

**Comment by jetBn** [comment]
> 把你的json文件发出来，目前主要关注在微信小程序，其他终端可能api会有差异导致错误。

能直接发 ？

**Comment by jetBn** [comment]
> 把你的json文件发出来，目前主要关注在微信小程序，其他终端可能api会有差异导致错误。
其实就是官网上随便弄个动画json出来然后支付宝小程序运行就报错。微信小程序正常

**Comment by jetBn** [comment]
有解决吗？

**Comment by landn172** [comment]
@jetBn 最近没时间看这个问题，你可以先自己尝试修复，并提交pr

**Comment by jetBn** [comment]
> @jetBn 最近没时间看这个问题，你可以先自己尝试修复，并提交pr

这加载成功，动画模糊是什么原因 ？无效参数 我找到了

**Comment by landn172** [comment]
@jetBn 可以参考html5绘制模糊的解决方案 https://www.html.cn/archives/9297

**Comment by jetBn** [comment]
> @jetBn 可以参考html5 canvas绘制模糊的解决方案 https://www.html.cn/archives/9297

你微信的不是已经做了适配了吗？支付宝的不应该一样吗 ？

**Comment by landn172** [comment]
微信什么没有处理

**Comment by jetBn** [comment]
就是canvas的  在微信小程序中不会模糊
