### ISSUE TITLE
在canvas中添加类型type="2d"无法渲染

### ISSUE THREAD

**Issue by GoTowere** [landn172/lottie-miniapp#148]
**bug描述**
现项目中遇到动画，并显示弹框，动画覆盖在弹框上，使用同层渲染(type="2d")后，动画无法渲染

**Comment by landn172** [comment]
![image](https://user-images.githubusercontent.com/4362412/82968595-3ce05380-a000-11ea-9389-613fa78b9ef3.png)
@GoTowere 看看https://developers.weixin.qq.com/miniprogram/dev/component/canvas.html
是否满足最低版本需求

**Comment by landn172** [comment]
注意到开启 type: 2d 之后需要使用新接口，需要修复下

**Comment by GoTowere** [comment]
我使用新接口后，无法渲染动画

**Comment by landn172** [comment]
> 我使用新接口后，无法渲染动画

这个我之后会修复，在此之前先不指定`type`

**Comment by GoTowere** [comment]
好的

**Comment by landn172** [comment]
@GoTowere try 1.9.0-0
