### ISSUE TITLE
引入后小程序分包增加256k，不知道有没有可去的冗余代码，不然这个库太大了

### ISSUE THREAD

**Issue by hotmaycold** [landn172/lottie-miniapp#15]
**bug描述**

**复现过程**

**期望**

**截图**

**错误设备信息**

**Comment by landn172** [comment]
![image](https://user-images.githubusercontent.com/4362412/50686289-b2d4cb00-1057-11e9-8480-a05494cb8503.png)
@hotmaycold 我看了下压缩后基本相同
由于基本移植了lottie-web所以大小差不多,但是增加了一些适配小程序差异性的代码所以可能会大一些

**Comment by hotmaycold** [comment]
> ![image](https://user-images.githubusercontent.com/4362412/50686289-b2d4cb00-1057-11e9-8480-a05494cb8503.png)
> @hotmaycold 我看了下压缩后基本相同
> 由于基本移植了lottie-web所以大小差不多,但是增加了一些适配小程序差异性的代码所以可能会大一些

感谢作者回复，可惜的是小程序不能gzip，web部分我引入的是lottie-web，gzipped之后60k
