### ISSUE TITLE
使用uni-app编译后再淘宝小程序运行没有动画

### ISSUE THREAD

**Issue by lixiaoyanlee** [landn172/lottie-miniapp#150]
**bug描述**
使用uni-app编译后再淘宝小程序运行没有动画，我看咱们的源码中 /untils/getEnvObj.js 
在uni-app编译即使我使用了环境变量的判断，但是执行的是还是 微信，即在uniapp下typeof wx !== 'undefined' && typeof wx.getSystemInfo === 'function' 为真；

还有ImagePreloader.js中使用createImageData(assetData)方法中的  new Promise(resolve => api.getImageInfo 感觉需要兼容，使用各种路径的地址都找不到图片

**期望**
希望作者可以兼容uniapp版编译的小程序~~

**截图**

**错误设备信息**
- 工具：淘宝小程序

**Comment by landn172** [comment]
@lixiaoyanlee 你把对应的json发出来
