### ISSUE TITLE
礼物播放报错了

### ISSUE THREAD

**Issue by felemon** [landn172/lottie-miniapp#151]
**截图**
![image](https://user-images.githubusercontent.com/4068351/84753635-d55f6780-aff1-11ea-9ce8-2a015332e29b.png)

**Comment by qlanto224** [comment]
兄弟我这边报错getFileSystemManager找不到,怎么解决啊

**Comment by landn172** [comment]
@qlanto224 支付宝还是微信，提供下对应的json文件方便排查

**Comment by qlanto224** [comment]
> @qlanto224 支付宝还是微信，提供下对应的json文件方便排查

uniapp  
[demo.zip](https://github.com/landn172/lottie-miniapp/files/4952698/demo.zip)

**Comment by landn172** [comment]
uniapp在微信中是好的

**Comment by qlanto224** [comment]
> uniapp在微信中是没问题，你是在什么平台有问题

示例项目uniapp平台  h5端报错:
![h5](https://user-images.githubusercontent.com/58463221/88158708-f5142c00-cc3e-11ea-991f-34bd4d329938.png)
给你的json 自己的demo 同样uniapp平台 h5 报错如下:
![image](https://user-images.githubusercontent.com/58463221/88159998-a8315500-cc40-11ea-8a8e-1208a0bca5e4.png)
uniapp平台 安卓 app中报错:
![image](https://user-images.githubusercontent.com/58463221/88161230-4d98f880-cc42-11ea-89d7-0f8ac64e2884.png)
同样的示例项目中也报上述错误

**Comment by landn172** [comment]
@qlanto224 只支持微信小程序，支付宝小程序修复了下，也已经支持
h5肯定不支持，完全没有做适配必要，有lottie-web方案。
