### ISSUE TITLE
请教下：我把lottie-miniapp引入项目中，想把它做成组件，引入不同的页面中，但是没有用

### ISSUE THREAD

**Issue by johanazhu** [landn172/lottie-miniapp#16]
我分别试了两种情况，一是把它做成组件，引入page时，展示不了
二我是在page页直接使用，虽然可以显示出，但是当数据出现，销毁lottie的时候就暂停到一边。
我是希望做成组件，在任何地方复用

**Comment by landn172** [comment]
@johanazhu 做成组件模式时注意scope： _wx.createCanvasContext('canvas', **this**)_
后续会考虑做一个component出来
