### ISSUE TITLE
使用过程中出现错误

### ISSUE THREAD

**Issue by gonglixin980926** [landn172/lottie-miniapp#177]
**bug描述**
![image](https://user-images.githubusercontent.com/40887236/167824142-3c3131c2-e910-4838-bcf3-3964ec636088.png)

**复现过程**

**期望**

**截图**

**错误设备信息**

**Comment by Rgoogle** [comment]
context问题把


    const uu='https://static.readboy.com/hub/web/speech-evaluation-mini/recording/recording.json'
        const query = wx.createSelectorQuery();

        query
            .select("#myCanvas")
            .fields({ node: true, size: true })
            .exec((res) => {
                console.log('query::',res)
                const canvas = res[0].node;
                const ctx = canvas.getContext("2d");

                const dpr = wx.getSystemInfoSync().pixelRatio;
                canvas.width = res[0].width * dpr;
                canvas.height = res[0].height * dpr;
                ctx.scale(dpr, dpr);

                lottie.loadAnimation({
                    renderer: "canvas", // 只支持canvas
                    loop: true,
                    autoplay: true,
                    // animationData: animationData,
                    path: uu,
                    rendererSettings: {
                        // 这里需要填 canvas
                        canvas: canvas,
                        context:  ctx,
                        clearCanvas: true,
                    },
                });
            });
//

**Comment by Rgoogle** [comment]
而且动画我感觉也有问题，动画不显示，这里只显示蓝色的线。。

**Comment by Rgoogle** [comment]
const uu='https://static.readboy.com/hub/web/speech-evaluation-mini/recording/recording.json'
    const query = wx.createSelectorQuery();

    query
        .select("#myCanvas")
        .fields({ node: true, size: true })
        .exec((res) => {
            console.log('query::',res)
            const canvas = res[0].node;
            const ctx = canvas.getContext("2d");

      //这里去掉设置宽高 可让动画有

            lottie.loadAnimation({
                renderer: "canvas", // 只支持canvas
                loop: true,
                autoplay: true,
                // animationData: animationData,
                path: uu,
                rendererSettings: {
                    // 这里需要填 canvas
                    canvas: canvas,
                    context:  ctx,
                    clearCanvas: true,
                },
            });
        });

**Comment by AllenGong0** [comment]
> const uu='https://static.readboy.com/hub/web/speech-evaluation-mini/recording/recording.json' const query = wx.createSelectorQuery();
> 
> ```
> query
>     .select("#myCanvas")
>     .fields({ node: true, size: true })
>     .exec((res) => {
>         console.log('query::',res)
>         const canvas = res[0].node;
>         const ctx = canvas.getContext("2d");
> 
>   //这里去掉设置宽高 可让动画有
> 
>         lottie.loadAnimation({
>             renderer: "canvas", // 只支持canvas
>             loop: true,
>             autoplay: true,
>             // animationData: animationData,
>             path: uu,
>             rendererSettings: {
>                 // 这里需要填 canvas
>                 canvas: canvas,
>                 context:  ctx,
>                 clearCanvas: true,
>             },
>         });
>     });
> ```

感谢大佬
