### ISSUE TITLE
CanvasContext 的一些 setXXX 方法已经不被支持，现在使用兼容web的写法

### ISSUE THREAD

**Issue by jiankafei** [landn172/lottie-miniapp#22]
如上

**Comment by landn172** [comment]
问题手动，之后有时间会处理一下。也欢迎提交pr

**Comment by jiankafei** [comment]
@landn172 我看了下，内部已经做了兼容处理，只是新旧api都使用了。

**Comment by xyx2011** [comment]
现在这个package 用demo 源码在微信小程序上是显示不出来动画的，用官方推荐的lottie-miniprogram 可以，但是官方那个写的太烂了，怎么破？

**Comment by landn172** [comment]
我有时间看看，开发工具是正常的吗？
