### ISSUE TITLE
引用本地的JSON不生效，path可否支持本地JSON文件

### ISSUE THREAD

**Issue by huangzizhao** [landn172/lottie-miniapp#23]
**bug描述**

**复现过程**

**期望**
希望path支持引用本地JSON，缩短请求造成的时间延迟（微信官方说4月会放出重构的Canvas，或许渲染会比之前的好，作者大大加油鸭~）

**截图**

**错误设备信息**
 - Device: [e.g. iPhone6s]
 - OS: [e.g. iOS12]

**Comment by landn172** [comment]
@huangzizhao 
**如果引用本地json请直接使用**
![image](https://user-images.githubusercontent.com/4362412/55301132-8b7e7600-546d-11e9-90f9-e3301345f9cd.png)
`path` 目前调用的是wx.request接口，不便修改。
