### ISSUE TITLE
是否可以支持 Taro 框架？

### ISSUE THREAD

**Issue by WangShuXian6** [landn172/lottie-miniapp#24]
试了下在 Taro 中使用，可能由于usingComponents 配置错误，无法运行

**Comment by landn172** [comment]
@WangShuXian6 提供相应代码或者错误信息，方便复现

**Comment by landn172** [comment]
@WangShuXian6 
taro下使用没问题， taro使用usingComponents是因为taro需要copy到项目中引入https://nervjs.github.io/taro/docs/mini-third-party.html
使用时是没问题的https://github.com/landn172/lottie-miniapp/tree/fix/taro/taro-example

**Comment by liuyunzyj** [comment]
@landn172 在taro中使用各个小程序都应该适配吧？

**Comment by liuyunzyj** [comment]
@landn172 不支持支付宝小程序吗？

**Comment by liuyunzyj** [comment]
@landn172  我使用的是taro框架搭建出来--微信小程序没有问题----支付宝小程序错误 
![image](https://user-images.githubusercontent.com/40293335/61920627-d9733880-af8c-11e9-8d29-9c176d4e037e.png)

**Comment by liuyunzyj** [comment]
@landn172 这个库只支持微信小程序？不支持支付宝小程序？![image](https://user-images.githubusercontent.com/40293335/61920746-34a52b00-af8d-11e9-893b-d3a83338cb6b.png)

**Comment by landn172** [comment]
目前只支持微信小程序，如果有强烈需求可以考虑多个平台

**Comment by liuyunzyj** [comment]
@landn172 是的，因为使用的是taro框架，麻烦官方快速推出

**Comment by liuyunzyj** [comment]
@landn172 目前我这边在支付宝小程序需要引用，有什么好的建议，我使用其他库或者是什么方式解决下，暂时的引入

**Comment by landn172** [comment]
如果想要快速适配的话，修改源码尝试把**wx.xxx**改成**my.xxxx**,但是不确定还有什么差异

**Comment by liuyunzyj** [comment]
我尝试过了，可能您这边wx的方法与my的方式有差异所以不适配

**Comment by liuyunzyj** [comment]
跟官方的平台的方法

**Comment by liuyunzyj** [comment]
@landn172 您这边是根据动画返回的JSON数据代表意思的规则来使用createCanvasContext，您这边能提供一下这个代表JSON返回的数据意思的参考文献吗？

**Comment by liuyunzyj** [comment]
@landn172 希望官方快点推出能支持支付宝小程序，谢谢
