### ISSUE TITLE
手机熄屏再亮屏，动画就不播放了？

### ISSUE THREAD

**Issue by xinyuanliu** [landn172/lottie-miniapp#25]
**bug描述**
使用该库在小程序中做动画，熄屏后，再亮屏，动画是停止播放的状态。

**期望**
熄屏再亮屏，动画持续在播放。

**错误设备信息**
Android和iOS都能出现。

提交的附件为动画json文件，请把后缀改成.json
[data.txt](https://github.com/landn172/lottie-miniapp/files/3121029/data.txt)

**Comment by landn172** [comment]
并没有写息屏暂停播放这个功能。
而且经过测试息屏后是可以播放的。

**Comment by landn172** [comment]
测试是息屏一段时间后，再打开之后此时动画是**暂停的**，再过一段时间4-5s动画会自动播放。
@xinyuanliu

**Comment by landn172** [comment]
请尝试下 lottie-miniapp@1.6.0
