### ISSUE TITLE
使用本地数据时报出 downloadFile:fail 

### ISSUE THREAD

**Issue by Jwiayou** [landn172/lottie-miniapp#27]
---
name: downloadFile:fail
about: 

---

**bug描述**
使用animationData本地数据未填写path，报出很多错误

**截图**
![image](https://user-images.githubusercontent.com/22660464/58247147-8530ba00-7d8b-11e9-86a8-bd2b97f547f4.png)

![image](https://user-images.githubusercontent.com/22660464/58247119-75b17100-7d8b-11e9-83fa-03862ad0b1e4.png)

![image](https://user-images.githubusercontent.com/22660464/58247072-5581b200-7d8b-11e9-89ae-35b07d6b3a06.png)

**错误设备信息**
 - Device: [华为p10]

**Comment by Jwiayou** [comment]
我有用到很多图片，是不是要报图片也放到组件的根目录

**Comment by landn172** [comment]
@Jwiayou 把具体的json发出来看看
