### ISSUE TITLE
为何我直接运行example报错 要怎么运行

### ISSUE THREAD

**Issue by kiros1986** [landn172/lottie-miniapp#29]
**截图**
![image](https://user-images.githubusercontent.com/8730378/59330134-34c1d200-8d23-11e9-8446-ce8fe75aa759.png)

**Comment by landn172** [comment]
调试请看：https://github.com/landn172/lottie-miniapp#%E8%B0%83%E8%AF%95
![image](https://user-images.githubusercontent.com/4362412/59401477-60999200-8dcd-11e9-9356-ed08b3ac7f64.png)
