### ISSUE TITLE
在uni-app 中出现错误

### ISSUE THREAD

**Issue by csj8520** [landn172/lottie-miniapp#30]
在微信开发者工具中 出现 Cannot read property 'replace' of null
在手机在上则是 出现 Cannot read property 'indexOf' of undefined

而且 手机上 动画位置出现偏移 整个动画偏移到右下角
有人遇见过这个问题吗？请问该如何解决

配置JSON在这 
[http://cdn.biglao.cn/images/1560142567371_data.json](http://cdn.biglao.cn/images/1560142567371_data.json)

使用这个JSON就没问题
[https://github.com/airbnb/lottie-web/blob/master/demo/gatin/data.json](https://github.com/airbnb/lottie-web/blob/master/demo/gatin/data.json)

![image](https://user-images.githubusercontent.com/39072685/59503083-0fbf9180-8ed2-11e9-92f1-a768651fef6e.png)
![image](https://user-images.githubusercontent.com/39072685/59503160-48f80180-8ed2-11e9-8a57-2f5c9c8a6286.png)
![image](https://user-images.githubusercontent.com/39072685/59503223-65943980-8ed2-11e9-9b3f-6902d61a11c6.png)

**Comment by landn172** [comment]
看了下就是你的json问题，导致图片下载错误的报错。
在lottie-web中运行mode=svg时，可以看到如下：
![image](https://user-images.githubusercontent.com/4362412/59591335-6de1b400-9120-11e9-81f9-a1c37353729d.png)
请先确保在web中可以正确运行

**Comment by csj8520** [comment]
@landn172 图片我是放在本地的服务里了，在web上测试可以正常渲染出来的
或者你可以试一下这一个json
[http://cdn.biglao.cn/images/1560509118343_data.json](http://cdn.biglao.cn/images/1560509118343_data.json)

**Comment by landn172** [comment]
@csj8520 我看了下图片路径会解析到 http://cdn.biglao.cn/images//images/img_0.png

**Comment by landn172** [comment]
其实动画还是在动的，只是没有展示图片导致看起来似乎因为微信小程序报错导致没有运行动画。并且我看了下lottie-web在没有图片加载不正确时会用红色区块代替图片显示。

**Comment by csj8520** [comment]
图片刚才我传上去了，现在应该可以看到 
但是在小程序里图片地址解析的是不对的 
![image](https://user-images.githubusercontent.com/39072685/59593794-2c9fd300-9125-11e9-93c3-f398c1457e51.png)
![image](https://user-images.githubusercontent.com/39072685/59593832-3d504900-9125-11e9-810c-22bfa0e1f951.png)

**Comment by landn172** [comment]
lottie-web源码在这里
https://github.com/airbnb/lottie-web/blob/6275f4c3c582c54000760e9f756df3398795a929/player/js/animation/AnimationItem.js#L498
小程序版本代码一致.web解析地址应该也是这个。
@csj8520  你的期望图片地址是什么？

**Comment by csj8520** [comment]
@landn172 在小程序里解析出的地址是这一个
http://cdn.biglao.cn/images/1560509118343_data.json/images/img_0.png
但是在h5里却是这一个
http://cdn.biglao.cn/images//images/img_0.png
这两个地址没有统一 当然最好是和h5一样

现在问题最大的还是这一个
![image](https://user-images.githubusercontent.com/39072685/59595521-91106180-9128-11e9-9714-8f23fc4a966c.png)

**Comment by landn172** [comment]
@csj8520 更新到v1.6.1
