### ISSUE TITLE
用官方web的data.jason测试 效果不如人意

### ISSUE THREAD

**Issue by kiros1986** [landn172/lottie-miniapp#32]
https://img-asset.chemm.com/test/lottie-demo/happy2016/data.json
效果为
https://img-asset.chemm.com/test/lottie-demo/happy2016/index.html

https://img-asset.chemm.com/test/lottie-demo/navidad/data.json
效果为
https://img-asset.chemm.com/test/lottie-demo/navidad/index.html

但是小程序上面全部变形了

**Comment by kiros1986** [comment]
请问好像不支持图片 甚至把里面有图片的转成base64 
效果例如
https://img-asset.chemm.com/test/lottie-demo/base64/index.html
数据
https://img-asset.chemm.com/test/lottie-demo/base64/data.json

**Comment by landn172** [comment]
1.动画变形有些是小程序canvas绘制和web绘制有差异导致的，这点之后有时间会修复。
2.支持图片，但暂不支持base64格式的图片。

**Comment by landn172** [comment]
Duplicate of #8

**Comment by landn172** [comment]
@kiros1986 已经修复不能加载base64图片，以及第一个案例变形问题。
请安装**lottie-miniapp@1.6.2**
第二个案例在lottie-web的canvas模式，也是变形，无法修复。
![image](https://user-images.githubusercontent.com/4362412/59742538-88db3200-92a0-11e9-88bd-01f2dd54c0f5.png)
