### ISSUE TITLE
npm构建后，引入lottie-miniapp 有报错 module "pages/index/lottie-miniapp" is not defined 

### ISSUE THREAD

**Issue by zzbo** [landn172/lottie-miniapp#34]
**bug描述**
npm i 安装 lottie-miniapp 后，再使用微信小程序的`构建npm` 。
pages/index/index.js 中
```js
import lottie from 'lottie-miniapp';
```

**截图**
Console 有报错：
module "pages/index/lottie-miniapp" is not defined 
![image](https://user-images.githubusercontent.com/3053640/60493758-1aef2b80-9ce0-11e9-92b7-82794fe9ecd3.png)

这里项目设置：
![image](https://user-images.githubusercontent.com/3053640/60493782-2b9fa180-9ce0-11e9-9905-1c6ed95fdaff.png)

但引用其他 npm 包是没有问题，这里应该怎么操作呢？

**Comment by VisonM** [comment]
你应该先看看如何在小程序里用npm [随便找了一篇](https://segmentfault.com/a/1190000016706395)

**Comment by zzbo** [comment]
> 你应该先看看如何在小程序里用npm [随便找了一篇](https://segmentfault.com/a/1190000016706395)

我看了这篇使用方法都对啊，但同样的方法同样的页面使用其他 npm 包是没有问题的。

**Comment by landn172** [comment]
开发工具貌似和我之前测试的不太一样
新开发工具构建之后的目录为如下
![image](https://user-images.githubusercontent.com/4362412/61097396-cb51f200-a48d-11e9-8cc4-4edf2dfb0930.png)
所以需要这样引入就可以了
![image](https://user-images.githubusercontent.com/4362412/61097452-f9cfcd00-a48d-11e9-9897-573e60167e6a.png)
@zzbo

**Comment by VisonM** [comment]
@landn172 正解

**Comment by VisonM** [comment]
@landn172 lottie在目前在小程序中复杂动画支持不稳定，lottie动画本身的交互也不复杂。对于动画效果是不是还是直接用gif图成本更低一点，作者怎么看？

**Comment by landn172** [comment]
@VisonM  要看情况具体分析，目前小程序上简单的lottie动画性能还行，复杂的动画比较卡就不太适合，当然也不是绝对的。
lottie主要的目的是减少动画文件大小（与gif同等的动画比较）、增强动画效果，但其实光lottie文件大小就要60K（#15）。
我们小程序也是两者结合使用的，在gif不大的情况下，还是优先gif吧。

**Comment by landn172** [comment]
@zzbo 这个问题是一个通用的问题，会在v1.7.0版本修复这个问题。到时候不用做修改
