### ISSUE TITLE
实机显示不出来？请问是怎么解决的呢？

### ISSUE THREAD

**Issue by cx091** [landn172/lottie-miniapp#5]
您好，我们刚刚试了一下发现在编译器中是能显示的，但是实机 就静止了

**Comment by landn172** [comment]
@cx091 你可以提供代码片段吗 https://developers.weixin.qq.com/miniprogram/dev/devtools/minicode.html
并且提供真机机型型号

**Comment by ahjsrhj** [comment]
同样不动，同时对比官方预览工具，动画变形
<img width="125" alt="2018-10-08 6 12 53" src="https://user-images.githubusercontent.com/8666955/46603502-d4401c80-cb25-11e8-8976-5466447138d4.png">
<img width="482" alt="2018-10-08 6 13 02" src="https://user-images.githubusercontent.com/8666955/46603504-d609e000-cb25-11e8-98b5-187d269f2f46.png">
手机型号：mi8，
代码基本拷贝自示例代码，lottie json来自官方示例文件。
https://github.com/airbnb/lottie-web/blob/master/demo/gatin/data.json
使用了wepy框架，版本：1.7.2

**Comment by liubiantao** [comment]
@landn172 有可以运行的代码片段吗? 我这边开发者工具可以运行, 安卓 iOS 都运行不了

**Comment by landn172** [comment]
@ahjsrhj 
手机不能运行问题已修复问题请更新到 lottie-miniapp@1.3.2
动画变形问题猜测因为小程序和h5的canvas实现有所差异导致的，example中的示例都可以完整运行，
后续有时间会跟踪并修复这个问题

**Comment by liubiantao** [comment]
@landn172 我自己的 demo 升级之后依然真机不显示, 或者说只显示第一帧动画. 
请问您的 example 应该怎么跑, 里面引用的不是`lottie-miniapp`, 而是`import lottie, { configProxy, proxyCtx } from '../lottie/index'`

**Comment by liubiantao** [comment]
example 跑起来了, 原来需要自己先编译一下. 真机 work, thx

**Comment by cx091** [comment]
感谢，现在跑起来了
