### ISSUE TITLE
支持多平台

### ISSUE THREAD

**Issue by landn172** [landn172/lottie-miniapp#52]
@landn172 在taro中使用各个小程序都应该适配吧？

_Originally posted by @liuyunzyj in https://github.com/landn172/lottie-miniapp/issues/24#issuecomment-515004151_

**Comment by landn172** [comment]
@liuyunzyj 支付宝测试了几个案例没问题，之后发布
![image](https://user-images.githubusercontent.com/4362412/61938182-15c18b80-afc3-11e9-8aa6-364c3ec69656.png)
![image](https://user-images.githubusercontent.com/4362412/61938252-3a1d6800-afc3-11e9-81ee-5aa426ab74d6.png)

**Comment by liuyunzyj** [comment]
@landn172 多谢

**Comment by landn172** [comment]
@liuyunzyj 已发布**lottie-miniapp@1.8.0**
使用时注意指定canvas的width和height，具体参考支付宝文档

**Comment by liuyunzyj** [comment]
@landn172 好的，您这边测试下，微信小程序这块，如果引用的json文件过大会出现加载不出来例如：https://labs.nearpod.com/bodymovin/demo/markus/isometric/markus2.json被引用会报错：
![image](https://user-images.githubusercontent.com/40293335/61939556-24f60880-afc6-11e9-8e8f-60c545b41686.png)
是对json大小有限制吗？

**Comment by liuyunzyj** [comment]
我使用的是taro框架

**Comment by landn172** [comment]
和taro无关，是lottie代码报错了，移植代码时候很多分支没有测试到，这个问题我看看

**Comment by liuyunzyj** [comment]
@landn172 这块建议区分下平台或者使用者传入当前平台
![image](https://user-images.githubusercontent.com/40293335/61941396-f9751d00-afc9-11e9-8092-bfcca894ee08.png)

**Comment by landn172** [comment]
这个问题是base64图片，目前只支持微信，其他平台都没相关api

**Comment by liuyunzyj** [comment]
@landn172 那为了防止错误的出现，使用者传入平台，这个错误就可以不报出来了吧

**Comment by chenhongen** [comment]
请问taro中如何引入？有没有文档供参考，谢谢~

**Comment by landn172** [comment]
@chenhongen https://github.com/landn172/lottie-miniapp/tree/fix/taro/taro-example

**Comment by chenhongen** [comment]
试了下，也遇到LZ的这个问题。
![1564455758(1)](https://user-images.githubusercontent.com/16499303/62097530-a34df580-b2b9-11e9-90a7-f3c3709dfa63.png)

**Comment by wanganxp** [comment]
是否支持uni-app框架？

**Comment by landn172** [comment]
@wanganxp 和框架无关，都支持。这里的多平台指的是除微信小程序之外的平台。

**Comment by landn172** [comment]
@chenhongen @liuyunzyj 报错问题已修复
lottie-miniapp@1.8.1

**Comment by chenhongen** [comment]
@landn172 我升级试了，动起来了。真棒~
但是有一个新问题：**autoplay这个属性设为false了，还是自动播放了**。。
我想通过play、stop控制它的播放与停止。

**Comment by clisstop** [comment]
> @liuyunzyj已发布**lottie-miniapp@1.8.0**
> 使用时注意指定画布的宽度和高度，具体参考支付宝文档

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
支付宝小程序提示  
 Cannot read property 'path' of undefined  只有个灰背景

**Comment by landn172** [comment]
@clisstop 你自己解决下代码报错 `Cannot read property 'path' of undefined`，这个应该不是lottie的问题

**Comment by laiyuknin** [comment]
> 

您好，为什么现在这个example访问不了了？

**Comment by laiyuknin** [comment]
> @chenhongen https://github.com/landn172/lottie-miniapp/tree/fix/taro/taro-example

您好，为什么这个example访问不了了

**Comment by landn172** [comment]
查看 [uniapp-example ](https://github.com/landn172/lottie-miniapp/tree/master/uniapp-example) 差不太多
