### ISSUE TITLE
PropertyFactory.js关键帧取值错误导致脚本执行报错

### ISSUE THREAD

**Issue by bling0390** [landn172/lottie-miniapp#55]
**bug描述**
关键帧取值错误导致脚本执行报错
> // src/lottie/utils/PropertyFactory.js at line 162
> keyValue = keyData.h === 1 ? keyData.s[i] : keyData.s[i] + (keyData.e[i] - keyData.s[i]) * perc;

对比官方lottie-web中的PropertyFactory.js发现：

> &gt;&gt;&gt; endValue = nextKeyData.s || keyData.e;
> keyValue = keyData.h === 1 ? keyData.s[i] : keyData.s[i] + (endValue[i] - keyData.s[i]) * perc;

**截图**
报错信息如下：
![image](https://user-images.githubusercontent.com/23183092/62192900-2601ae00-b3a9-11e9-9802-e8b1d7b64897.png)

**错误设备信息**
 - Device:  微信开发者工具
 - OS: MacOS

**Comment by landn172** [comment]
@bling0390 把json发出来

**Comment by bling0390** [comment]
[test.log](https://github.com/landn172/lottie-miniapp/files/3450566/test.log)

**Comment by XuXianTao** [comment]
遇到相同的问题了，希望能把修复及时更新到npm包上
感谢🙇‍（我用`git+https://github.com/landn172/lottie-miniapp.git#fix-bug`安装分支`#fix-bug`但是node_modules里面没有代码）
![image](https://user-images.githubusercontent.com/32198066/62260131-7e858980-b443-11e9-930f-dd1d50f0b208.png)

**Comment by landn172** [comment]
@XuXianTao 我在集中统一修复其他反馈的问题，预计今天或者明天会发一版

**Comment by XuXianTao** [comment]
十分感谢👌

**Comment by landn172** [comment]
@XuXianTao @bling0390 报错问题已修复
lottie-miniapp@1.8.1

**Comment by bling0390** [comment]
Thanks.
