### ISSUE TITLE
怎么运行

### ISSUE THREAD

**Issue by qi19901212** [landn172/lottie-miniapp#6]
你这采用什么框架么？不是普通小程序么？

**Comment by landn172** [comment]
@qi19901212 目前开发工具支持npm方式引入,请参照文档
https://developers.weixin.qq.com/miniprogram/dev/devtools/npm.html
如果你使用其他都构建工具像taro,mpvue等会自动打包
或者可以使用[jgb-cli](https://www.npmjs.com/package/jgb-cli)
