### ISSUE TITLE
通过canvas渲染后 如何修改对象的位置 postion

### ISSUE THREAD

**Issue by zsbox** [landn172/lottie-miniapp#67]
就是在小程序中通过canvas渲染之后 获取到这个对象 可以修改对象的一些属性 比如position scale opacity width height rotate等 
注意不是对canvas进行操作 是对渲染对对象进行操作

**Comment by landn172** [comment]
请将你的意图描述清晰

**Comment by zsbox** [comment]
已更新 请看

**Comment by landn172** [comment]
@zsbox 不支持，lottie-web也没有这个功能。而且这个需求比较奇怪，如果你要改的话，建议改json文件。
