### ISSUE TITLE
调试工具上能显示，真机不显示。真机要打开调试工具才显示是什么个情况？

### ISSUE THREAD

**Issue by lixsh8** [landn172/lottie-miniapp#69]
调试工具上能显示，真机不显示。真机上要打开调试才显示是什么个情况？

**Comment by landn172** [comment]
看下是否在真机报错。

**Comment by lixsh8** [comment]
不开调试也看不到有没有报错。开了调试动画又能显示，

**Comment by lixsh8** [comment]
![IMG_2286(20190813-161835)](https://user-images.githubusercontent.com/6927216/62926369-f742f900-bde6-11e9-81c0-e31804aa4e4e.jpg)
![IMG_2285(20190813-161904)](https://user-images.githubusercontent.com/6927216/62926371-f7db8f80-bde6-11e9-8186-5a49afba6e8e.jpg)

**Comment by landn172** [comment]
请求的url是否在域名白名单里 @lixsh8

**Comment by lixsh8** [comment]
可以了谢谢。但是有个警告
![image](https://user-images.githubusercontent.com/6927216/62929740-a7b3fb80-bded-11e9-9076-7c2d17c4373d.png)

**Comment by landn172** [comment]
这个warning没事，只是一个优化。

**Comment by JJH0901** [comment]
您好，你这个问题是怎么解决的

**Comment by landn172** [comment]
@JJH0901 json中可能会有图片下载，如果图片不在download白名单时，就会白屏。开发工具中
![image](https://user-images.githubusercontent.com/4362412/71884259-ee2a3e00-3172-11ea-981c-a94abbc1d612.png)取消勾选看看是否能复现这个问题。
