### ISSUE TITLE
请问支持位图么？多图片是否显示有问题。

### ISSUE THREAD

**Issue by bili-jing** [landn172/lottie-miniapp#72]
json: https://ddpicture.oss-cn-shenzhen.aliyuncs.com/1565782313691_bubble.json
不显示呢.请问是json问题还是我使用上的问题么.也没有错误信息提示.

**Comment by landn172** [comment]
@bili-jing 是否是最新版本，我看了下最新版本是没问题的，并确保基础库版本高于**2.0**, 以及是否配置域名。
![image](https://user-images.githubusercontent.com/4362412/63068115-9af5eb80-bf44-11e9-80aa-efe0206259a7.png)

**Comment by bili-jing** [comment]
@landn172 基础库是最新的。2.8.0. 模拟器上面是可以的。但是预览和真机调试不行呢。也没有报什么错误。不清楚具体原因。麻烦老哥可以帮我看下么。谢谢了

**Comment by landn172** [comment]
@bili-jing 已修复**lottie-miniapp@1.8.3**
