### ISSUE TITLE
在很多安卓机器上滑动的时候好卡，去掉动画就没有卡顿问题

### ISSUE THREAD

**Issue by lixsh8** [landn172/lottie-miniapp#88]
在很多安卓机器上滑动的时候好卡，去掉动画就没有卡顿问题。特别是配置不是很好的机器上，有什么可以优化的吗？

**Comment by landn172** [comment]
@lixsh8  这问题也有遇到过，尽量使用component，会有不错的性能提升。
lottie本质还是通过计算每一帧的动画再绘制，不可避免会有性能瓶颈，尤其是复杂动画。
