### ISSUE TITLE
请问下对应的api有哪些呢

### ISSUE THREAD

**Issue by bili-jing** [landn172/lottie-miniapp#92]
需要关闭动画，开始下一个动画。能否先加载动画图片资源，在需要播放的时候播放呢

**Comment by landn172** [comment]
你是希望一个可以预加载api吗？

**Comment by bili-jing** [comment]
如果这行的通的话。想询问下关闭动画的api有么，或者是哪一个呢。感谢老哥的回复。

**Comment by landn172** [comment]
相关api参考 https://github.com/airbnb/lottie-web。如果lottie-web没有也不会考虑支持。

**Comment by bili-jing** [comment]
好的 谢谢老哥。我想问下如何监听动画结束呢。web的onComplete在小程序里是如何使用的呢

**Comment by landn172** [comment]
`lottie.loadAnimation`返回`animationItem` , 所以如下
```js
const item = lottie.loadAnimation();
item.addEventListener('loopComplete', ()=>{
    console.log('loopComplete')
})
```
